### ISSUE TITLE
Ensure diagrams can be easily expanded and viewed

### ISSUE THREAD

**Issue by ckamps** [ckamps/aws-foundation-journey#6]
Currently, clicking on links to diagrams takes you to the underlying diagram file vs being able easily explode and zoom into the diagrams.

**Comment by ckamps** [comment]
Partially addressed via the following references to diagrams, but it would great if we could find a means to use relative links vs the use of fully qualified URLs.

```
![alt text](https://github.com/ckamps/aws-foundation-journey/raw/master/images/dev-fast-follow-ons.png "Initial Development Environment with Fast Follow-On Capabilities")
```

**Comment by collinforrester** [comment]
I don't think it gets any better than relative paths.  clicking the image will always go to the source and not any type of preview.. i think this can be closed.

**Comment by ckamps** [comment]
As mentioned in the earlier comment, I viewed customer experience over the awkardness of using fully qualified links for larger diagrams that can't be easily viewed without expanding them.
